version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    environment:
      - CI=true
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: "Run Yarn"
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: "Run Tests"
          command: yarn test
      - run:
          name: "Build"
          command: yarn build
workflows:
  build:
    jobs:
      - build