name: Build
on:
  push:
    branches: [ main, develop, "feat/github-pages" ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16.13.2
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - name: Upload build
        if: github.ref == 'refs/heads/feat/github-pages'
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact_${{ github.sha }}
          overwrite: true
          path: build
  deploy:
    if: github.ref == 'refs/heads/feat/github-pages'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_${{ github.sha }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4